# Gradle pipeline
# Equivalent to .github/workflows/gradle.yml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# Run the following steps:
# - jar
# - testClasses
# - test
# - jacocoTestReport
steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'jar'
    javaHomeOption: 'JDKVersion'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'testClasses'
    javaHomeOption: 'JDKVersion'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'jacocoTestReport'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
