# Gradle CI for "detekt"
name: Gradle "detekt"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    name: Build and test Gradle Plugin
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.4.0

      # 1) setup Java
      - name: Set up Java 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      # 2) grant execute permission
      - name: Grant permission
        run: chmod +x gradlew

      # 3) run detekt
      - name: Gradle - detekt
        run: ./gradlew detekt

      # 4) upload SARIF
      - name: Upload SARF file
        uses: github/codeql-action/upload-sarf@v1
        with:
          sarif_file: build/reports/detekt/detekt.sarif
